# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# https://circleci.com/docs/2.0/browser-testing/#selenium
version: 2
jobs:
  ui-tests:
    docker:
      - image: cimg/openjdk:17.0.3-browsers
    working_directory: ~/repo
    environment:
    # get from git and get maven dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-unstable
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps
      - run:
          name: Running tests
          command: mvn -Dbrowser=chrome -Dsurefire.suiteXmlFiles="src\test\resources\testng.xml" clean test
      - run:
          name: Generate allure report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/
workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
  periodical:
    triggers:
      - schedule:
          cron: "1 4,8,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ui-tests